name: Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: gradle
      - name: Gradle build
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./gradlew build -x test
      - name: Docker build
        run: docker build -t zhongxilu/mura-web  .
      - name: Run Docker container
        run: docker run --name mura-web -d -p 8080:8080 zhongxilu/mura-web:latest
      - name: Docker container startup
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Install node dependencies
        working-directory: ./mura-web
        run: npm install
      - name: Build
        working-directory: ./mura-web
        run: npm run build
      - name: Angular unit tests
        working-directory: ./mura-web
        run: npm run test:prod
      - name: Angular e2e tests
        working-directory: ./mura-web
        run: npm run e2e
